# Generated by Django 5.2.8 on 2025-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('meta_title', models.CharField(help_text='60 chars max', max_length=60)),
                ('meta_description', models.CharField(help_text='160 chars max', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('canonical_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'SEO Meta Tags',
            },
        ),
        migrations.RemoveField(
            model_name='aboutcard',
            name='about',
        ),
        migrations.DeleteModel(
            name='FooterQuickLink',
        ),
        migrations.RemoveField(
            model_name='whyitem',
            name='why',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='developer_name',
        ),
        migrations.DeleteModel(
            name='AboutCard',
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='WhyItem',
        ),
        migrations.DeleteModel(
            name='WhyKemet',
        ),
    ]
